---
kind: pipeline
type: exec
name: default
concurrency:
  limit: 1

clone:
  disable: true

steps:
- name: pull
  commands:
  - eval `ssh-agent -s`
  - ssh-add /home/dreamland/.ssh/drone
  - cd /var/www/dreamland_web
  - git pull
  - kill -9 $SSH_AGENT_PID
  
- name: update_website
  commands:
  - /usr/bin/node /var/www/dreamland_web/website.js/main.js /home/dreamland/runtime
  
- name: update_helps
  commands:
  - /usr/bin/node /var/www/dreamland_web/help.js/help.js /var/www/dreamland_web/static/help
  
- name: restart_searcher
  commands:
  - systemctl restart dreamland-searcher.service

trigger:
  branch:
  - master
  event:
  - push
  
