---
kind: pipeline
type: exec
name: default
concurrency:
  limit: 1

clone:
  disable: true

steps:
- name: pull
  commands:
  - eval `ssh-agent -s`
  - ssh-add /home/dreamland/.ssh/drone
  - cd /var/www/dreamland_web
  - git pull
  - kill -9 $SSH_AGENT_PID
  
- name: update_website
  commands:
  - /usr/bin/node /var/www/dreamland_web/website.js/main.js /home/dreamland/runtime
  
- name: update_helps
  commands:
  - /usr/bin/node /var/www/dreamland_web/help.js/help.js /var/www/dreamland_web/static/help
  
- name: restart_searcher
  commands:
  - sudo systemctl restart dreamland-searcher.service

- name: discord_failure
  commands:
  - >
    echo "{\"embeds\":[{\"color\": 13632027,\"description\":\"Latest dreamland_web failed to build, what have you done, mate?\n\",\"title\":\"Deployment failed!\"}], \"username\":\"Drone Bot\", \"avatar_url\": \"https://docs.drone.io/logo.svg\"}" \
    | /home/dreamland/runtime/bin/idiscord-code
  when:
    status:
      - failure
  
- name: discord_success
  commands:
  - >
    echo "{\"embeds\":[{\"color\": 8311585,\"description\":\"DreamLand website is updated, enjoy!\n\",\"title\":\"Deployment successful\"}], \"username\":\"Drone Bot\", \"avatar_url\": \"https://docs.drone.io/logo.svg\"}" \
    | /home/dreamland/runtime/bin/idiscord-code
  when:
    status:
      - success
      
trigger:
  branch:
  - master
  event:
  - push
  
